# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
# the first 10 terms will be: 1,1,2,3,5,8,13,21,34,55,89,...
# By considering the terms in the Fibonacci sequence whose values do not exceed N,
# find the sum of the even-valued terms.

# Input Format
# First line contains T that denotes the number of test cases.
# This is followed by T lines, each containing an integer, N.
#
# Output Format
# Print the required answer for each test case.


def even_fibonacci_sum(n):
    a = 1
    b = 1
    even_sum = 0
    while True:
        c = a + b
        if c >= n:
            return even_sum
        if c % 2 == 0:
            even_sum += c
        a, b = b, c


t = int(input().strip())
for t1 in range(t):
    n = int(input().strip())
    print(even_fibonacci_sum(n))

